### ISSUE TITLE
minimum char count to start search

### ISSUE THREAD

**Issue by danwguy** [kadoshms/ionic2-autocomplete#51]
First off, this is absolutely awesome, thank you! A quick feature that could be great is making a minLevel or minCharCount to start the search. That way, when you have to make an expensive api call to get results you aren't making it when there's only 1 or 2 characters in the search bar. I know it's possible to just check the length of the string in the getResults method, but if it were built in it would be a lot smoother. Maybe adding it to the DOM something like...
`<ion-auto-complete [dataProvider]="search" (itemSelected)="itemSelected($event)" [minLevel]="2"></ion-auto-complete>`
That way it wouldn't even start searching for results until there is at least 2 characters in the search bar.

**Comment by kadoshms** [comment]
Cool, I will totally consider it.

**Comment by kamok** [comment]
@danwguy People normally uses what's known as debounce in order to save some money on the number of api requests. For example, my end users type slow. I want to delay the function call to my expensive api by like 2 seconds. Eg, only fire api call when they haven't type for 2 seconds. You can read more about it here: https://stackoverflow.com/questions/32051273/angular2-and-debounce

However, it's not working for me right now with the library, trying t figure it out.

**Comment by kamok** [comment]
@danwguy I actually figured out debounce if you still want to do a higher debounce than 250 milliseconds. I set mine to 750 with `options` for my slow typers. If you read the current README more carefully, there's a link to the ionic docs with the options there, and you can pass it onto the component with the options argument.
