### ISSUE TITLE
Feature request: ngModel

### ISSUE THREAD

**Issue by bushybuffalo** [kadoshms/ionic2-autocomplete#53]
Hey,

I'd like to use the ngModel directive on the ion-auto-complete tag, as it is available on ion-searchbar and ion-input, but it seems not to be implemented (i.e., I get the following error when setting this directive: "No value accessor for form control with name: 'foo' ")

I would be really grateful if you could make this possible !

**Comment by kadoshms** [comment]
@bushybuffalo could you please give more details about what you are trying to achieve? 
Basically, you have access to the actual value through the `ionAutoInput` event, and within the service through `getResults` as the first param.
Isn't it what you need?

**Comment by bushybuffalo** [comment]
@kadoshms I have a set of inputs that the user has to fill in to enable another part of the screen.
What I usually do is set my inputs as required, set a ngModel for all of them, and use form validation to enable or disable the other part of the screen. This way I do not need to write any validation code in the class, only in the template.

**Comment by kadoshms** [comment]
@bushybuffalo I understand, and will totally consider this (it might take some time though cause I am in a very busy time :) )
If it can't wait, you are most welcome to fork the repository and commit your changes, I'll be happy to assist you with that.

**Comment by bushybuffalo** [comment]
Well I would like to be able to use it as soon as possible indeed, I have forked the project and I am trying to implement it, I will keep you informed !

**Comment by kadoshms** [comment]
Thanks for your contribution!
If you wish to use your update, you can easily build the source code and use it.
In the meantime, open a pull request and then I will be to review it.

If you need more assitance please contact me dirrctly via email.

**Comment by bogomips** [comment]
Hello @bushybuffalo I was going to write the ngModel support by myself but I found you, thanks for saving me some time :)
I needed another feature though: for the countries (like the example) my api takes the standard country code like IT while I show to users "Italy" so I want to have the possibility of showing something to user while I save something different in my model.
I don't have time to fork and pull request, even because they are few lines of code, so below there is my patch.

My selection is --->  Object {id: "IT", name: "Italia"}

`
public updateModel(selection) {

    let ret;    

    if ('returnedProperty' in this.dataProvider === false || !selection)
      ret = this.keyword;
    else
      ret = selection[this.dataProvider.returnedProperty];

    this.onChangeCallback(ret);
  }

......

  public select(selection: any): void { 
    this.keyword = this.dataProvider.labelAttribute == null || selection[this.dataProvider.labelAttribute] == null
      ? selection : selection[this.dataProvider.labelAttribute];
    this.hideItemList();
    
    // emit selection event
    this.itemSelected.emit(selection);        
    this.updateModel(selection); <--- just added the value to pass
  }

//then it is enough to add  the property  

@Injectable()
export class TestProvider implements AutoCompleteService {

  public labelAttribute:string = "name";
  public returnedProperty="id";
`

I guess this would be useful for many users.
@kadoshms  I think the @bushybuffalo's PR is essential, are you going to review it any soon?

Thanks all

**Comment by bogomips** [comment]
Hello @bushybuffalo I was going to write the ngModel support by myself but I found you, thanks for saving me some time :)
I needed another feature though: for the countries (like the example) my api takes the standard country code like IT while I show to users "Italy" so I want to have the possibility of showing something to user while I save something different in my model.
I don't have time to fork and pull request, even because they are few lines of code, so below there is my patch.

My selection is --->  Object {id: "IT", name: "Italia"}

`
public updateModel(selection) {

    let ret;    

    if ('returnedProperty' in this.dataProvider === false || !selection)
      ret = this.keyword;
    else
      ret = selection[this.dataProvider.returnedProperty];

    this.onChangeCallback(ret);
  }

......

  public select(selection: any): void { 
    this.keyword = this.dataProvider.labelAttribute == null || selection[this.dataProvider.labelAttribute] == null
      ? selection : selection[this.dataProvider.labelAttribute];
    this.hideItemList();
    
    // emit selection event
    this.itemSelected.emit(selection);        
    this.updateModel(selection); <--- just added the value to pass
  }

//then it is enough to add  the property  

@Injectable()
export class TestProvider implements AutoCompleteService {

  public labelAttribute:string = "name";
  public returnedProperty="id";
`

I guess this would be useful for many users.
@kadoshms  I think the @bushybuffalo's PR is essential, are you going to review it any soon?

Thanks all
